id: binance_flow
namespace: company.team


tasks:

  - id: print_requirements
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    namespaceFiles:
      enabled: true
    commands:
      - cat requirements.txt

  - id: binance
    type: io.kestra.plugin.scripts.python.Commands
    env:
      BUCKET_URL: "{{kv('BUCKET_URL')}}"
    #  DESTINATION__FILESYSTEM__CREDENTIALS__CLIENT_EMAIL: "{{kv('client_email')}}"
    #  DESTINATION__FILESYSTEM__CREDENTIALS__PROJECT_ID: "{{kv('project_id')}}"
    #  DESTINATION__FILESYSTEM__CREDENTIALS__PRIVATE_KEY: "{{kv('private_key')}}"
    #  GOOGLE_APPLICATION_CREDENTIALS: "{{ kv('key_file') }}"
      DESTINATION__FILESYSTEM__CREDENTIALS: "{{ kv('key_file') }}"
    warningOnStdErr: false
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    containerImage: python:3.11-slim
    beforeCommands:
      - pip install --upgrade pip
      - pip install -r requirements.txt > /dev/null
    namespaceFiles:
      enabled: true
#      include:
#        - binance_flow.py
    commands:
      - python binance_flow.py
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/10 * * * *"