
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            #tests:
            #    - unique
            #    - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            #tests:
            #    - unique
            #    - not_null

    - name: binance
      description: 'Cleaned Binance market data'
      columns:
          - name: trade_id
            description: Unique id of each trade
            tests:
              - unique
              - not_null
          - name: price
          - name: quantity
          - name: first_trade_id
          - name: last_trade_it
          - name: trade_timestamp
          - name: trade_date
          - name: exchange_info
          - name: is_buyer_maker 

    - name: binance_totals
      description: 'Aggregated Binance market data'
      columns:
          - name: trade_day_hour
            description: Unique id of each trade
          - name: total_volume
          - name: average_price
          - name: exchange_info
          - name: total_number_of_trades

sources:
  - name: elegant
    #database: "{{ env_var('DBT_DATABASE', 'stellar-day-445214-e5') }}"
    #schema: "{{ env_var('DBT_SCHEMA', 'sql_database_data') }}"
    #database: elegant-karma-454910-u2
    #schema: elegant
      # loaded_at_field: record_loaded_at
    tables:
      - name: binance_data
        #freshness:
        #error_after: {count: 6, period: hour}

  - name: elegant
    loader: gcloud storage
    tables:
      - name: binance_ext
        description: This is an external table based on all files in the GCS bucket
        external:
          location: gs://elegant-bucket/aggtrade/binance_data/*
          options: 
            format: json

        columns:
          - name: _dlt_id
            data_type: string
          - name: _dlt_load_id
            data_type: NUMERIC
          - name: m
            data_type: bool
          - name: t
            data_type: integer
          - name: q
            data_type: NUMERIC
          - name: l
            data_type: integer
          - name: p
            data_type: NUMERIC
          - name: f
            data_type: integer
          - name: a
            data_type: integer